// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageAliveACK.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "MessageAliveACK.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* MessageAliveACK_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MessageAliveACK_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_MessageAliveACK_2eproto() {
  protobuf_AddDesc_MessageAliveACK_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "MessageAliveACK.proto");
  GOOGLE_CHECK(file != NULL);
  MessageAliveACK_descriptor_ = file->message_type(0);
  static const int MessageAliveACK_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessageAliveACK, session_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessageAliveACK, local_time_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessageAliveACK, server_time_),
  };
  MessageAliveACK_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MessageAliveACK_descriptor_,
      MessageAliveACK::default_instance_,
      MessageAliveACK_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessageAliveACK, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessageAliveACK, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MessageAliveACK));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_MessageAliveACK_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MessageAliveACK_descriptor_, &MessageAliveACK::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_MessageAliveACK_2eproto() {
  delete MessageAliveACK::default_instance_;
  delete MessageAliveACK_reflection_;
}

void protobuf_AddDesc_MessageAliveACK_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\025MessageAliveACK.proto\"N\n\017MessageAliveA"
    "CK\022\022\n\nsession_id\030\001 \002(\003\022\022\n\nlocal_time\030\002 \002"
    "(\003\022\023\n\013server_time\030\003 \002(\003", 103);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "MessageAliveACK.proto", &protobuf_RegisterTypes);
  MessageAliveACK::default_instance_ = new MessageAliveACK();
  MessageAliveACK::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_MessageAliveACK_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_MessageAliveACK_2eproto {
  StaticDescriptorInitializer_MessageAliveACK_2eproto() {
    protobuf_AddDesc_MessageAliveACK_2eproto();
  }
} static_descriptor_initializer_MessageAliveACK_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int MessageAliveACK::kSessionIdFieldNumber;
const int MessageAliveACK::kLocalTimeFieldNumber;
const int MessageAliveACK::kServerTimeFieldNumber;
#endif  // !_MSC_VER

MessageAliveACK::MessageAliveACK()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:MessageAliveACK)
}

void MessageAliveACK::InitAsDefaultInstance() {
}

MessageAliveACK::MessageAliveACK(const MessageAliveACK& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:MessageAliveACK)
}

void MessageAliveACK::SharedCtor() {
  _cached_size_ = 0;
  session_id_ = GOOGLE_LONGLONG(0);
  local_time_ = GOOGLE_LONGLONG(0);
  server_time_ = GOOGLE_LONGLONG(0);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MessageAliveACK::~MessageAliveACK() {
  // @@protoc_insertion_point(destructor:MessageAliveACK)
  SharedDtor();
}

void MessageAliveACK::SharedDtor() {
  if (this != default_instance_) {
  }
}

void MessageAliveACK::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MessageAliveACK::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MessageAliveACK_descriptor_;
}

const MessageAliveACK& MessageAliveACK::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_MessageAliveACK_2eproto();
  return *default_instance_;
}

MessageAliveACK* MessageAliveACK::default_instance_ = NULL;

MessageAliveACK* MessageAliveACK::New() const {
  return new MessageAliveACK;
}

void MessageAliveACK::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<MessageAliveACK*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  ZR_(session_id_, server_time_);

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool MessageAliveACK::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:MessageAliveACK)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int64 session_id = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &session_id_)));
          set_has_session_id();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_local_time;
        break;
      }

      // required int64 local_time = 2;
      case 2: {
        if (tag == 16) {
         parse_local_time:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &local_time_)));
          set_has_local_time();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_server_time;
        break;
      }

      // required int64 server_time = 3;
      case 3: {
        if (tag == 24) {
         parse_server_time:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &server_time_)));
          set_has_server_time();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MessageAliveACK)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MessageAliveACK)
  return false;
#undef DO_
}

void MessageAliveACK::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MessageAliveACK)
  // required int64 session_id = 1;
  if (has_session_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->session_id(), output);
  }

  // required int64 local_time = 2;
  if (has_local_time()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(2, this->local_time(), output);
  }

  // required int64 server_time = 3;
  if (has_server_time()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(3, this->server_time(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:MessageAliveACK)
}

::google::protobuf::uint8* MessageAliveACK::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:MessageAliveACK)
  // required int64 session_id = 1;
  if (has_session_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->session_id(), target);
  }

  // required int64 local_time = 2;
  if (has_local_time()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(2, this->local_time(), target);
  }

  // required int64 server_time = 3;
  if (has_server_time()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(3, this->server_time(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MessageAliveACK)
  return target;
}

int MessageAliveACK::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int64 session_id = 1;
    if (has_session_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->session_id());
    }

    // required int64 local_time = 2;
    if (has_local_time()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->local_time());
    }

    // required int64 server_time = 3;
    if (has_server_time()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->server_time());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MessageAliveACK::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const MessageAliveACK* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MessageAliveACK*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MessageAliveACK::MergeFrom(const MessageAliveACK& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_session_id()) {
      set_session_id(from.session_id());
    }
    if (from.has_local_time()) {
      set_local_time(from.local_time());
    }
    if (from.has_server_time()) {
      set_server_time(from.server_time());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void MessageAliveACK::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MessageAliveACK::CopyFrom(const MessageAliveACK& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MessageAliveACK::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  return true;
}

void MessageAliveACK::Swap(MessageAliveACK* other) {
  if (other != this) {
    std::swap(session_id_, other->session_id_);
    std::swap(local_time_, other->local_time_);
    std::swap(server_time_, other->server_time_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata MessageAliveACK::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MessageAliveACK_descriptor_;
  metadata.reflection = MessageAliveACK_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
