// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageSyncBlock.proto

#ifndef PROTOBUF_MessageSyncBlock_2eproto__INCLUDED
#define PROTOBUF_MessageSyncBlock_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_MessageSyncBlock_2eproto();
void protobuf_AssignDesc_MessageSyncBlock_2eproto();
void protobuf_ShutdownFile_MessageSyncBlock_2eproto();

class MessageSyncBlock;

// ===================================================================

class MessageSyncBlock : public ::google::protobuf::Message {
 public:
  MessageSyncBlock();
  virtual ~MessageSyncBlock();

  MessageSyncBlock(const MessageSyncBlock& from);

  inline MessageSyncBlock& operator=(const MessageSyncBlock& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MessageSyncBlock& default_instance();

  void Swap(MessageSyncBlock* other);

  // implements Message ----------------------------------------------

  MessageSyncBlock* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MessageSyncBlock& from);
  void MergeFrom(const MessageSyncBlock& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 status = 1;
  inline bool has_status() const;
  inline void clear_status();
  static const int kStatusFieldNumber = 1;
  inline ::google::protobuf::int32 status() const;
  inline void set_status(::google::protobuf::int32 value);

  // required string path = 2;
  inline bool has_path() const;
  inline void clear_path();
  static const int kPathFieldNumber = 2;
  inline const ::std::string& path() const;
  inline void set_path(const ::std::string& value);
  inline void set_path(const char* value);
  inline void set_path(const char* value, size_t size);
  inline ::std::string* mutable_path();
  inline ::std::string* release_path();
  inline void set_allocated_path(::std::string* path);

  // required int64 size = 3;
  inline bool has_size() const;
  inline void clear_size();
  static const int kSizeFieldNumber = 3;
  inline ::google::protobuf::int64 size() const;
  inline void set_size(::google::protobuf::int64 value);

  // required int64 id = 4;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 4;
  inline ::google::protobuf::int64 id() const;
  inline void set_id(::google::protobuf::int64 value);

  // required int64 index = 5;
  inline bool has_index() const;
  inline void clear_index();
  static const int kIndexFieldNumber = 5;
  inline ::google::protobuf::int64 index() const;
  inline void set_index(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:MessageSyncBlock)
 private:
  inline void set_has_status();
  inline void clear_has_status();
  inline void set_has_path();
  inline void clear_has_path();
  inline void set_has_size();
  inline void clear_has_size();
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_index();
  inline void clear_has_index();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* path_;
  ::google::protobuf::int64 size_;
  ::google::protobuf::int64 id_;
  ::google::protobuf::int64 index_;
  ::google::protobuf::int32 status_;
  friend void  protobuf_AddDesc_MessageSyncBlock_2eproto();
  friend void protobuf_AssignDesc_MessageSyncBlock_2eproto();
  friend void protobuf_ShutdownFile_MessageSyncBlock_2eproto();

  void InitAsDefaultInstance();
  static MessageSyncBlock* default_instance_;
};
// ===================================================================


// ===================================================================

// MessageSyncBlock

// required int32 status = 1;
inline bool MessageSyncBlock::has_status() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MessageSyncBlock::set_has_status() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MessageSyncBlock::clear_has_status() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MessageSyncBlock::clear_status() {
  status_ = 0;
  clear_has_status();
}
inline ::google::protobuf::int32 MessageSyncBlock::status() const {
  // @@protoc_insertion_point(field_get:MessageSyncBlock.status)
  return status_;
}
inline void MessageSyncBlock::set_status(::google::protobuf::int32 value) {
  set_has_status();
  status_ = value;
  // @@protoc_insertion_point(field_set:MessageSyncBlock.status)
}

// required string path = 2;
inline bool MessageSyncBlock::has_path() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MessageSyncBlock::set_has_path() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MessageSyncBlock::clear_has_path() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MessageSyncBlock::clear_path() {
  if (path_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    path_->clear();
  }
  clear_has_path();
}
inline const ::std::string& MessageSyncBlock::path() const {
  // @@protoc_insertion_point(field_get:MessageSyncBlock.path)
  return *path_;
}
inline void MessageSyncBlock::set_path(const ::std::string& value) {
  set_has_path();
  if (path_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    path_ = new ::std::string;
  }
  path_->assign(value);
  // @@protoc_insertion_point(field_set:MessageSyncBlock.path)
}
inline void MessageSyncBlock::set_path(const char* value) {
  set_has_path();
  if (path_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    path_ = new ::std::string;
  }
  path_->assign(value);
  // @@protoc_insertion_point(field_set_char:MessageSyncBlock.path)
}
inline void MessageSyncBlock::set_path(const char* value, size_t size) {
  set_has_path();
  if (path_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    path_ = new ::std::string;
  }
  path_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:MessageSyncBlock.path)
}
inline ::std::string* MessageSyncBlock::mutable_path() {
  set_has_path();
  if (path_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    path_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:MessageSyncBlock.path)
  return path_;
}
inline ::std::string* MessageSyncBlock::release_path() {
  clear_has_path();
  if (path_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = path_;
    path_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void MessageSyncBlock::set_allocated_path(::std::string* path) {
  if (path_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete path_;
  }
  if (path) {
    set_has_path();
    path_ = path;
  } else {
    clear_has_path();
    path_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:MessageSyncBlock.path)
}

// required int64 size = 3;
inline bool MessageSyncBlock::has_size() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MessageSyncBlock::set_has_size() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MessageSyncBlock::clear_has_size() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MessageSyncBlock::clear_size() {
  size_ = GOOGLE_LONGLONG(0);
  clear_has_size();
}
inline ::google::protobuf::int64 MessageSyncBlock::size() const {
  // @@protoc_insertion_point(field_get:MessageSyncBlock.size)
  return size_;
}
inline void MessageSyncBlock::set_size(::google::protobuf::int64 value) {
  set_has_size();
  size_ = value;
  // @@protoc_insertion_point(field_set:MessageSyncBlock.size)
}

// required int64 id = 4;
inline bool MessageSyncBlock::has_id() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void MessageSyncBlock::set_has_id() {
  _has_bits_[0] |= 0x00000008u;
}
inline void MessageSyncBlock::clear_has_id() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void MessageSyncBlock::clear_id() {
  id_ = GOOGLE_LONGLONG(0);
  clear_has_id();
}
inline ::google::protobuf::int64 MessageSyncBlock::id() const {
  // @@protoc_insertion_point(field_get:MessageSyncBlock.id)
  return id_;
}
inline void MessageSyncBlock::set_id(::google::protobuf::int64 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:MessageSyncBlock.id)
}

// required int64 index = 5;
inline bool MessageSyncBlock::has_index() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void MessageSyncBlock::set_has_index() {
  _has_bits_[0] |= 0x00000010u;
}
inline void MessageSyncBlock::clear_has_index() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void MessageSyncBlock::clear_index() {
  index_ = GOOGLE_LONGLONG(0);
  clear_has_index();
}
inline ::google::protobuf::int64 MessageSyncBlock::index() const {
  // @@protoc_insertion_point(field_get:MessageSyncBlock.index)
  return index_;
}
inline void MessageSyncBlock::set_index(::google::protobuf::int64 value) {
  set_has_index();
  index_ = value;
  // @@protoc_insertion_point(field_set:MessageSyncBlock.index)
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MessageSyncBlock_2eproto__INCLUDED
