// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageRequestGetToken.proto

#ifndef PROTOBUF_MessageRequestGetToken_2eproto__INCLUDED
#define PROTOBUF_MessageRequestGetToken_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_MessageRequestGetToken_2eproto();
void protobuf_AssignDesc_MessageRequestGetToken_2eproto();
void protobuf_ShutdownFile_MessageRequestGetToken_2eproto();

class MessageRequestGetToken;

// ===================================================================

class MessageRequestGetToken : public ::google::protobuf::Message {
 public:
  MessageRequestGetToken();
  virtual ~MessageRequestGetToken();

  MessageRequestGetToken(const MessageRequestGetToken& from);

  inline MessageRequestGetToken& operator=(const MessageRequestGetToken& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MessageRequestGetToken& default_instance();

  void Swap(MessageRequestGetToken* other);

  // implements Message ----------------------------------------------

  MessageRequestGetToken* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MessageRequestGetToken& from);
  void MergeFrom(const MessageRequestGetToken& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int64 index = 1;
  inline bool has_index() const;
  inline void clear_index();
  static const int kIndexFieldNumber = 1;
  inline ::google::protobuf::int64 index() const;
  inline void set_index(::google::protobuf::int64 value);

  // required string request_id = 2;
  inline bool has_request_id() const;
  inline void clear_request_id();
  static const int kRequestIdFieldNumber = 2;
  inline const ::std::string& request_id() const;
  inline void set_request_id(const ::std::string& value);
  inline void set_request_id(const char* value);
  inline void set_request_id(const char* value, size_t size);
  inline ::std::string* mutable_request_id();
  inline ::std::string* release_request_id();
  inline void set_allocated_request_id(::std::string* request_id);

  // required int64 block_id = 3;
  inline bool has_block_id() const;
  inline void clear_block_id();
  static const int kBlockIdFieldNumber = 3;
  inline ::google::protobuf::int64 block_id() const;
  inline void set_block_id(::google::protobuf::int64 value);

  // required int64 client_id = 4;
  inline bool has_client_id() const;
  inline void clear_client_id();
  static const int kClientIdFieldNumber = 4;
  inline ::google::protobuf::int64 client_id() const;
  inline void set_client_id(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:MessageRequestGetToken)
 private:
  inline void set_has_index();
  inline void clear_has_index();
  inline void set_has_request_id();
  inline void clear_has_request_id();
  inline void set_has_block_id();
  inline void clear_has_block_id();
  inline void set_has_client_id();
  inline void clear_has_client_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int64 index_;
  ::std::string* request_id_;
  ::google::protobuf::int64 block_id_;
  ::google::protobuf::int64 client_id_;
  friend void  protobuf_AddDesc_MessageRequestGetToken_2eproto();
  friend void protobuf_AssignDesc_MessageRequestGetToken_2eproto();
  friend void protobuf_ShutdownFile_MessageRequestGetToken_2eproto();

  void InitAsDefaultInstance();
  static MessageRequestGetToken* default_instance_;
};
// ===================================================================


// ===================================================================

// MessageRequestGetToken

// required int64 index = 1;
inline bool MessageRequestGetToken::has_index() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MessageRequestGetToken::set_has_index() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MessageRequestGetToken::clear_has_index() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MessageRequestGetToken::clear_index() {
  index_ = GOOGLE_LONGLONG(0);
  clear_has_index();
}
inline ::google::protobuf::int64 MessageRequestGetToken::index() const {
  // @@protoc_insertion_point(field_get:MessageRequestGetToken.index)
  return index_;
}
inline void MessageRequestGetToken::set_index(::google::protobuf::int64 value) {
  set_has_index();
  index_ = value;
  // @@protoc_insertion_point(field_set:MessageRequestGetToken.index)
}

// required string request_id = 2;
inline bool MessageRequestGetToken::has_request_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MessageRequestGetToken::set_has_request_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MessageRequestGetToken::clear_has_request_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MessageRequestGetToken::clear_request_id() {
  if (request_id_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    request_id_->clear();
  }
  clear_has_request_id();
}
inline const ::std::string& MessageRequestGetToken::request_id() const {
  // @@protoc_insertion_point(field_get:MessageRequestGetToken.request_id)
  return *request_id_;
}
inline void MessageRequestGetToken::set_request_id(const ::std::string& value) {
  set_has_request_id();
  if (request_id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    request_id_ = new ::std::string;
  }
  request_id_->assign(value);
  // @@protoc_insertion_point(field_set:MessageRequestGetToken.request_id)
}
inline void MessageRequestGetToken::set_request_id(const char* value) {
  set_has_request_id();
  if (request_id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    request_id_ = new ::std::string;
  }
  request_id_->assign(value);
  // @@protoc_insertion_point(field_set_char:MessageRequestGetToken.request_id)
}
inline void MessageRequestGetToken::set_request_id(const char* value, size_t size) {
  set_has_request_id();
  if (request_id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    request_id_ = new ::std::string;
  }
  request_id_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:MessageRequestGetToken.request_id)
}
inline ::std::string* MessageRequestGetToken::mutable_request_id() {
  set_has_request_id();
  if (request_id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    request_id_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:MessageRequestGetToken.request_id)
  return request_id_;
}
inline ::std::string* MessageRequestGetToken::release_request_id() {
  clear_has_request_id();
  if (request_id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = request_id_;
    request_id_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void MessageRequestGetToken::set_allocated_request_id(::std::string* request_id) {
  if (request_id_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete request_id_;
  }
  if (request_id) {
    set_has_request_id();
    request_id_ = request_id;
  } else {
    clear_has_request_id();
    request_id_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:MessageRequestGetToken.request_id)
}

// required int64 block_id = 3;
inline bool MessageRequestGetToken::has_block_id() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MessageRequestGetToken::set_has_block_id() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MessageRequestGetToken::clear_has_block_id() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MessageRequestGetToken::clear_block_id() {
  block_id_ = GOOGLE_LONGLONG(0);
  clear_has_block_id();
}
inline ::google::protobuf::int64 MessageRequestGetToken::block_id() const {
  // @@protoc_insertion_point(field_get:MessageRequestGetToken.block_id)
  return block_id_;
}
inline void MessageRequestGetToken::set_block_id(::google::protobuf::int64 value) {
  set_has_block_id();
  block_id_ = value;
  // @@protoc_insertion_point(field_set:MessageRequestGetToken.block_id)
}

// required int64 client_id = 4;
inline bool MessageRequestGetToken::has_client_id() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void MessageRequestGetToken::set_has_client_id() {
  _has_bits_[0] |= 0x00000008u;
}
inline void MessageRequestGetToken::clear_has_client_id() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void MessageRequestGetToken::clear_client_id() {
  client_id_ = GOOGLE_LONGLONG(0);
  clear_has_client_id();
}
inline ::google::protobuf::int64 MessageRequestGetToken::client_id() const {
  // @@protoc_insertion_point(field_get:MessageRequestGetToken.client_id)
  return client_id_;
}
inline void MessageRequestGetToken::set_client_id(::google::protobuf::int64 value) {
  set_has_client_id();
  client_id_ = value;
  // @@protoc_insertion_point(field_set:MessageRequestGetToken.client_id)
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MessageRequestGetToken_2eproto__INCLUDED
