// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageQueryFile.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "MessageQueryFile.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* MessageQueryFile_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MessageQueryFile_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_MessageQueryFile_2eproto() {
  protobuf_AddDesc_MessageQueryFile_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "MessageQueryFile.proto");
  GOOGLE_CHECK(file != NULL);
  MessageQueryFile_descriptor_ = file->message_type(0);
  static const int MessageQueryFile_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessageQueryFile, file_name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessageQueryFile, query_id_),
  };
  MessageQueryFile_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MessageQueryFile_descriptor_,
      MessageQueryFile::default_instance_,
      MessageQueryFile_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessageQueryFile, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessageQueryFile, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MessageQueryFile));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_MessageQueryFile_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MessageQueryFile_descriptor_, &MessageQueryFile::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_MessageQueryFile_2eproto() {
  delete MessageQueryFile::default_instance_;
  delete MessageQueryFile_reflection_;
}

void protobuf_AddDesc_MessageQueryFile_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\026MessageQueryFile.proto\"7\n\020MessageQuery"
    "File\022\021\n\tfile_name\030\001 \002(\t\022\020\n\010query_id\030\002 \002("
    "\003", 81);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "MessageQueryFile.proto", &protobuf_RegisterTypes);
  MessageQueryFile::default_instance_ = new MessageQueryFile();
  MessageQueryFile::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_MessageQueryFile_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_MessageQueryFile_2eproto {
  StaticDescriptorInitializer_MessageQueryFile_2eproto() {
    protobuf_AddDesc_MessageQueryFile_2eproto();
  }
} static_descriptor_initializer_MessageQueryFile_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int MessageQueryFile::kFileNameFieldNumber;
const int MessageQueryFile::kQueryIdFieldNumber;
#endif  // !_MSC_VER

MessageQueryFile::MessageQueryFile()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:MessageQueryFile)
}

void MessageQueryFile::InitAsDefaultInstance() {
}

MessageQueryFile::MessageQueryFile(const MessageQueryFile& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:MessageQueryFile)
}

void MessageQueryFile::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  file_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  query_id_ = GOOGLE_LONGLONG(0);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MessageQueryFile::~MessageQueryFile() {
  // @@protoc_insertion_point(destructor:MessageQueryFile)
  SharedDtor();
}

void MessageQueryFile::SharedDtor() {
  if (file_name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete file_name_;
  }
  if (this != default_instance_) {
  }
}

void MessageQueryFile::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MessageQueryFile::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MessageQueryFile_descriptor_;
}

const MessageQueryFile& MessageQueryFile::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_MessageQueryFile_2eproto();
  return *default_instance_;
}

MessageQueryFile* MessageQueryFile::default_instance_ = NULL;

MessageQueryFile* MessageQueryFile::New() const {
  return new MessageQueryFile;
}

void MessageQueryFile::Clear() {
  if (_has_bits_[0 / 32] & 3) {
    if (has_file_name()) {
      if (file_name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        file_name_->clear();
      }
    }
    query_id_ = GOOGLE_LONGLONG(0);
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool MessageQueryFile::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:MessageQueryFile)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string file_name = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_file_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->file_name().data(), this->file_name().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "file_name");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_query_id;
        break;
      }

      // required int64 query_id = 2;
      case 2: {
        if (tag == 16) {
         parse_query_id:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &query_id_)));
          set_has_query_id();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MessageQueryFile)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MessageQueryFile)
  return false;
#undef DO_
}

void MessageQueryFile::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MessageQueryFile)
  // required string file_name = 1;
  if (has_file_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->file_name().data(), this->file_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "file_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->file_name(), output);
  }

  // required int64 query_id = 2;
  if (has_query_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(2, this->query_id(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:MessageQueryFile)
}

::google::protobuf::uint8* MessageQueryFile::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:MessageQueryFile)
  // required string file_name = 1;
  if (has_file_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->file_name().data(), this->file_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "file_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->file_name(), target);
  }

  // required int64 query_id = 2;
  if (has_query_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(2, this->query_id(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MessageQueryFile)
  return target;
}

int MessageQueryFile::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string file_name = 1;
    if (has_file_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->file_name());
    }

    // required int64 query_id = 2;
    if (has_query_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->query_id());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MessageQueryFile::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const MessageQueryFile* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MessageQueryFile*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MessageQueryFile::MergeFrom(const MessageQueryFile& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_file_name()) {
      set_file_name(from.file_name());
    }
    if (from.has_query_id()) {
      set_query_id(from.query_id());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void MessageQueryFile::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MessageQueryFile::CopyFrom(const MessageQueryFile& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MessageQueryFile::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void MessageQueryFile::Swap(MessageQueryFile* other) {
  if (other != this) {
    std::swap(file_name_, other->file_name_);
    std::swap(query_id_, other->query_id_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata MessageQueryFile::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MessageQueryFile_descriptor_;
  metadata.reflection = MessageQueryFile_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
