// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageRequestPutToken.proto

#ifndef PROTOBUF_MessageRequestPutToken_2eproto__INCLUDED
#define PROTOBUF_MessageRequestPutToken_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_MessageRequestPutToken_2eproto();
void protobuf_AssignDesc_MessageRequestPutToken_2eproto();
void protobuf_ShutdownFile_MessageRequestPutToken_2eproto();

class MessageRequestPutToken;

// ===================================================================

class MessageRequestPutToken : public ::google::protobuf::Message {
 public:
  MessageRequestPutToken();
  virtual ~MessageRequestPutToken();

  MessageRequestPutToken(const MessageRequestPutToken& from);

  inline MessageRequestPutToken& operator=(const MessageRequestPutToken& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MessageRequestPutToken& default_instance();

  void Swap(MessageRequestPutToken* other);

  // implements Message ----------------------------------------------

  MessageRequestPutToken* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MessageRequestPutToken& from);
  void MergeFrom(const MessageRequestPutToken& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int64 index = 1;
  inline bool has_index() const;
  inline void clear_index();
  static const int kIndexFieldNumber = 1;
  inline ::google::protobuf::int64 index() const;
  inline void set_index(::google::protobuf::int64 value);

  // required string request_id = 2;
  inline bool has_request_id() const;
  inline void clear_request_id();
  static const int kRequestIdFieldNumber = 2;
  inline const ::std::string& request_id() const;
  inline void set_request_id(const ::std::string& value);
  inline void set_request_id(const char* value);
  inline void set_request_id(const char* value, size_t size);
  inline ::std::string* mutable_request_id();
  inline ::std::string* release_request_id();
  inline void set_allocated_request_id(::std::string* request_id);

  // @@protoc_insertion_point(class_scope:MessageRequestPutToken)
 private:
  inline void set_has_index();
  inline void clear_has_index();
  inline void set_has_request_id();
  inline void clear_has_request_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int64 index_;
  ::std::string* request_id_;
  friend void  protobuf_AddDesc_MessageRequestPutToken_2eproto();
  friend void protobuf_AssignDesc_MessageRequestPutToken_2eproto();
  friend void protobuf_ShutdownFile_MessageRequestPutToken_2eproto();

  void InitAsDefaultInstance();
  static MessageRequestPutToken* default_instance_;
};
// ===================================================================


// ===================================================================

// MessageRequestPutToken

// required int64 index = 1;
inline bool MessageRequestPutToken::has_index() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MessageRequestPutToken::set_has_index() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MessageRequestPutToken::clear_has_index() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MessageRequestPutToken::clear_index() {
  index_ = GOOGLE_LONGLONG(0);
  clear_has_index();
}
inline ::google::protobuf::int64 MessageRequestPutToken::index() const {
  // @@protoc_insertion_point(field_get:MessageRequestPutToken.index)
  return index_;
}
inline void MessageRequestPutToken::set_index(::google::protobuf::int64 value) {
  set_has_index();
  index_ = value;
  // @@protoc_insertion_point(field_set:MessageRequestPutToken.index)
}

// required string request_id = 2;
inline bool MessageRequestPutToken::has_request_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MessageRequestPutToken::set_has_request_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MessageRequestPutToken::clear_has_request_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MessageRequestPutToken::clear_request_id() {
  if (request_id_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    request_id_->clear();
  }
  clear_has_request_id();
}
inline const ::std::string& MessageRequestPutToken::request_id() const {
  // @@protoc_insertion_point(field_get:MessageRequestPutToken.request_id)
  return *request_id_;
}
inline void MessageRequestPutToken::set_request_id(const ::std::string& value) {
  set_has_request_id();
  if (request_id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    request_id_ = new ::std::string;
  }
  request_id_->assign(value);
  // @@protoc_insertion_point(field_set:MessageRequestPutToken.request_id)
}
inline void MessageRequestPutToken::set_request_id(const char* value) {
  set_has_request_id();
  if (request_id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    request_id_ = new ::std::string;
  }
  request_id_->assign(value);
  // @@protoc_insertion_point(field_set_char:MessageRequestPutToken.request_id)
}
inline void MessageRequestPutToken::set_request_id(const char* value, size_t size) {
  set_has_request_id();
  if (request_id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    request_id_ = new ::std::string;
  }
  request_id_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:MessageRequestPutToken.request_id)
}
inline ::std::string* MessageRequestPutToken::mutable_request_id() {
  set_has_request_id();
  if (request_id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    request_id_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:MessageRequestPutToken.request_id)
  return request_id_;
}
inline ::std::string* MessageRequestPutToken::release_request_id() {
  clear_has_request_id();
  if (request_id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = request_id_;
    request_id_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void MessageRequestPutToken::set_allocated_request_id(::std::string* request_id) {
  if (request_id_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete request_id_;
  }
  if (request_id) {
    set_has_request_id();
    request_id_ = request_id;
  } else {
    clear_has_request_id();
    request_id_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:MessageRequestPutToken.request_id)
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MessageRequestPutToken_2eproto__INCLUDED
