// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageGetTokenACK.proto

#ifndef PROTOBUF_MessageGetTokenACK_2eproto__INCLUDED
#define PROTOBUF_MessageGetTokenACK_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_MessageGetTokenACK_2eproto();
void protobuf_AssignDesc_MessageGetTokenACK_2eproto();
void protobuf_ShutdownFile_MessageGetTokenACK_2eproto();

class MessageGetTokenACK;

// ===================================================================

class MessageGetTokenACK : public ::google::protobuf::Message {
 public:
  MessageGetTokenACK();
  virtual ~MessageGetTokenACK();

  MessageGetTokenACK(const MessageGetTokenACK& from);

  inline MessageGetTokenACK& operator=(const MessageGetTokenACK& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MessageGetTokenACK& default_instance();

  void Swap(MessageGetTokenACK* other);

  // implements Message ----------------------------------------------

  MessageGetTokenACK* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MessageGetTokenACK& from);
  void MergeFrom(const MessageGetTokenACK& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string token = 1;
  inline bool has_token() const;
  inline void clear_token();
  static const int kTokenFieldNumber = 1;
  inline const ::std::string& token() const;
  inline void set_token(const ::std::string& value);
  inline void set_token(const char* value);
  inline void set_token(const char* value, size_t size);
  inline ::std::string* mutable_token();
  inline ::std::string* release_token();
  inline void set_allocated_token(::std::string* token);

  // required int64 expire = 2;
  inline bool has_expire() const;
  inline void clear_expire();
  static const int kExpireFieldNumber = 2;
  inline ::google::protobuf::int64 expire() const;
  inline void set_expire(::google::protobuf::int64 value);

  // required int64 index = 3;
  inline bool has_index() const;
  inline void clear_index();
  static const int kIndexFieldNumber = 3;
  inline ::google::protobuf::int64 index() const;
  inline void set_index(::google::protobuf::int64 value);

  // required int64 client_id = 4;
  inline bool has_client_id() const;
  inline void clear_client_id();
  static const int kClientIdFieldNumber = 4;
  inline ::google::protobuf::int64 client_id() const;
  inline void set_client_id(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:MessageGetTokenACK)
 private:
  inline void set_has_token();
  inline void clear_has_token();
  inline void set_has_expire();
  inline void clear_has_expire();
  inline void set_has_index();
  inline void clear_has_index();
  inline void set_has_client_id();
  inline void clear_has_client_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* token_;
  ::google::protobuf::int64 expire_;
  ::google::protobuf::int64 index_;
  ::google::protobuf::int64 client_id_;
  friend void  protobuf_AddDesc_MessageGetTokenACK_2eproto();
  friend void protobuf_AssignDesc_MessageGetTokenACK_2eproto();
  friend void protobuf_ShutdownFile_MessageGetTokenACK_2eproto();

  void InitAsDefaultInstance();
  static MessageGetTokenACK* default_instance_;
};
// ===================================================================


// ===================================================================

// MessageGetTokenACK

// required string token = 1;
inline bool MessageGetTokenACK::has_token() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MessageGetTokenACK::set_has_token() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MessageGetTokenACK::clear_has_token() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MessageGetTokenACK::clear_token() {
  if (token_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    token_->clear();
  }
  clear_has_token();
}
inline const ::std::string& MessageGetTokenACK::token() const {
  // @@protoc_insertion_point(field_get:MessageGetTokenACK.token)
  return *token_;
}
inline void MessageGetTokenACK::set_token(const ::std::string& value) {
  set_has_token();
  if (token_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    token_ = new ::std::string;
  }
  token_->assign(value);
  // @@protoc_insertion_point(field_set:MessageGetTokenACK.token)
}
inline void MessageGetTokenACK::set_token(const char* value) {
  set_has_token();
  if (token_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    token_ = new ::std::string;
  }
  token_->assign(value);
  // @@protoc_insertion_point(field_set_char:MessageGetTokenACK.token)
}
inline void MessageGetTokenACK::set_token(const char* value, size_t size) {
  set_has_token();
  if (token_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    token_ = new ::std::string;
  }
  token_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:MessageGetTokenACK.token)
}
inline ::std::string* MessageGetTokenACK::mutable_token() {
  set_has_token();
  if (token_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    token_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:MessageGetTokenACK.token)
  return token_;
}
inline ::std::string* MessageGetTokenACK::release_token() {
  clear_has_token();
  if (token_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = token_;
    token_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void MessageGetTokenACK::set_allocated_token(::std::string* token) {
  if (token_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete token_;
  }
  if (token) {
    set_has_token();
    token_ = token;
  } else {
    clear_has_token();
    token_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:MessageGetTokenACK.token)
}

// required int64 expire = 2;
inline bool MessageGetTokenACK::has_expire() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MessageGetTokenACK::set_has_expire() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MessageGetTokenACK::clear_has_expire() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MessageGetTokenACK::clear_expire() {
  expire_ = GOOGLE_LONGLONG(0);
  clear_has_expire();
}
inline ::google::protobuf::int64 MessageGetTokenACK::expire() const {
  // @@protoc_insertion_point(field_get:MessageGetTokenACK.expire)
  return expire_;
}
inline void MessageGetTokenACK::set_expire(::google::protobuf::int64 value) {
  set_has_expire();
  expire_ = value;
  // @@protoc_insertion_point(field_set:MessageGetTokenACK.expire)
}

// required int64 index = 3;
inline bool MessageGetTokenACK::has_index() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MessageGetTokenACK::set_has_index() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MessageGetTokenACK::clear_has_index() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MessageGetTokenACK::clear_index() {
  index_ = GOOGLE_LONGLONG(0);
  clear_has_index();
}
inline ::google::protobuf::int64 MessageGetTokenACK::index() const {
  // @@protoc_insertion_point(field_get:MessageGetTokenACK.index)
  return index_;
}
inline void MessageGetTokenACK::set_index(::google::protobuf::int64 value) {
  set_has_index();
  index_ = value;
  // @@protoc_insertion_point(field_set:MessageGetTokenACK.index)
}

// required int64 client_id = 4;
inline bool MessageGetTokenACK::has_client_id() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void MessageGetTokenACK::set_has_client_id() {
  _has_bits_[0] |= 0x00000008u;
}
inline void MessageGetTokenACK::clear_has_client_id() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void MessageGetTokenACK::clear_client_id() {
  client_id_ = GOOGLE_LONGLONG(0);
  clear_has_client_id();
}
inline ::google::protobuf::int64 MessageGetTokenACK::client_id() const {
  // @@protoc_insertion_point(field_get:MessageGetTokenACK.client_id)
  return client_id_;
}
inline void MessageGetTokenACK::set_client_id(::google::protobuf::int64 value) {
  set_has_client_id();
  client_id_ = value;
  // @@protoc_insertion_point(field_set:MessageGetTokenACK.client_id)
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MessageGetTokenACK_2eproto__INCLUDED
