// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageAlive.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "MessageAlive.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* MessageAlive_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MessageAlive_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_MessageAlive_2eproto() {
  protobuf_AddDesc_MessageAlive_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "MessageAlive.proto");
  GOOGLE_CHECK(file != NULL);
  MessageAlive_descriptor_ = file->message_type(0);
  static const int MessageAlive_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessageAlive, session_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessageAlive, local_time_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessageAlive, disk_space_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessageAlive, block_num_),
  };
  MessageAlive_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MessageAlive_descriptor_,
      MessageAlive::default_instance_,
      MessageAlive_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessageAlive, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessageAlive, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MessageAlive));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_MessageAlive_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MessageAlive_descriptor_, &MessageAlive::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_MessageAlive_2eproto() {
  delete MessageAlive::default_instance_;
  delete MessageAlive_reflection_;
}

void protobuf_AddDesc_MessageAlive_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\022MessageAlive.proto\"]\n\014MessageAlive\022\022\n\n"
    "session_id\030\001 \002(\003\022\022\n\nlocal_time\030\002 \002(\003\022\022\n\n"
    "disk_space\030\003 \002(\003\022\021\n\tblock_num\030\004 \002(\003", 115);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "MessageAlive.proto", &protobuf_RegisterTypes);
  MessageAlive::default_instance_ = new MessageAlive();
  MessageAlive::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_MessageAlive_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_MessageAlive_2eproto {
  StaticDescriptorInitializer_MessageAlive_2eproto() {
    protobuf_AddDesc_MessageAlive_2eproto();
  }
} static_descriptor_initializer_MessageAlive_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int MessageAlive::kSessionIdFieldNumber;
const int MessageAlive::kLocalTimeFieldNumber;
const int MessageAlive::kDiskSpaceFieldNumber;
const int MessageAlive::kBlockNumFieldNumber;
#endif  // !_MSC_VER

MessageAlive::MessageAlive()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:MessageAlive)
}

void MessageAlive::InitAsDefaultInstance() {
}

MessageAlive::MessageAlive(const MessageAlive& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:MessageAlive)
}

void MessageAlive::SharedCtor() {
  _cached_size_ = 0;
  session_id_ = GOOGLE_LONGLONG(0);
  local_time_ = GOOGLE_LONGLONG(0);
  disk_space_ = GOOGLE_LONGLONG(0);
  block_num_ = GOOGLE_LONGLONG(0);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MessageAlive::~MessageAlive() {
  // @@protoc_insertion_point(destructor:MessageAlive)
  SharedDtor();
}

void MessageAlive::SharedDtor() {
  if (this != default_instance_) {
  }
}

void MessageAlive::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MessageAlive::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MessageAlive_descriptor_;
}

const MessageAlive& MessageAlive::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_MessageAlive_2eproto();
  return *default_instance_;
}

MessageAlive* MessageAlive::default_instance_ = NULL;

MessageAlive* MessageAlive::New() const {
  return new MessageAlive;
}

void MessageAlive::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<MessageAlive*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  ZR_(session_id_, block_num_);

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool MessageAlive::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:MessageAlive)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int64 session_id = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &session_id_)));
          set_has_session_id();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_local_time;
        break;
      }

      // required int64 local_time = 2;
      case 2: {
        if (tag == 16) {
         parse_local_time:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &local_time_)));
          set_has_local_time();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_disk_space;
        break;
      }

      // required int64 disk_space = 3;
      case 3: {
        if (tag == 24) {
         parse_disk_space:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &disk_space_)));
          set_has_disk_space();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_block_num;
        break;
      }

      // required int64 block_num = 4;
      case 4: {
        if (tag == 32) {
         parse_block_num:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &block_num_)));
          set_has_block_num();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MessageAlive)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MessageAlive)
  return false;
#undef DO_
}

void MessageAlive::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MessageAlive)
  // required int64 session_id = 1;
  if (has_session_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->session_id(), output);
  }

  // required int64 local_time = 2;
  if (has_local_time()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(2, this->local_time(), output);
  }

  // required int64 disk_space = 3;
  if (has_disk_space()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(3, this->disk_space(), output);
  }

  // required int64 block_num = 4;
  if (has_block_num()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(4, this->block_num(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:MessageAlive)
}

::google::protobuf::uint8* MessageAlive::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:MessageAlive)
  // required int64 session_id = 1;
  if (has_session_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->session_id(), target);
  }

  // required int64 local_time = 2;
  if (has_local_time()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(2, this->local_time(), target);
  }

  // required int64 disk_space = 3;
  if (has_disk_space()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(3, this->disk_space(), target);
  }

  // required int64 block_num = 4;
  if (has_block_num()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(4, this->block_num(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MessageAlive)
  return target;
}

int MessageAlive::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int64 session_id = 1;
    if (has_session_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->session_id());
    }

    // required int64 local_time = 2;
    if (has_local_time()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->local_time());
    }

    // required int64 disk_space = 3;
    if (has_disk_space()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->disk_space());
    }

    // required int64 block_num = 4;
    if (has_block_num()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->block_num());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MessageAlive::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const MessageAlive* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MessageAlive*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MessageAlive::MergeFrom(const MessageAlive& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_session_id()) {
      set_session_id(from.session_id());
    }
    if (from.has_local_time()) {
      set_local_time(from.local_time());
    }
    if (from.has_disk_space()) {
      set_disk_space(from.disk_space());
    }
    if (from.has_block_num()) {
      set_block_num(from.block_num());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void MessageAlive::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MessageAlive::CopyFrom(const MessageAlive& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MessageAlive::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000000f) != 0x0000000f) return false;

  return true;
}

void MessageAlive::Swap(MessageAlive* other) {
  if (other != this) {
    std::swap(session_id_, other->session_id_);
    std::swap(local_time_, other->local_time_);
    std::swap(disk_space_, other->disk_space_);
    std::swap(block_num_, other->block_num_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata MessageAlive::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MessageAlive_descriptor_;
  metadata.reflection = MessageAlive_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
