// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageToken.proto

#ifndef PROTOBUF_MessageToken_2eproto__INCLUDED
#define PROTOBUF_MessageToken_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_MessageToken_2eproto();
void protobuf_AssignDesc_MessageToken_2eproto();
void protobuf_ShutdownFile_MessageToken_2eproto();

class MessageToken;

// ===================================================================

class MessageToken : public ::google::protobuf::Message {
 public:
  MessageToken();
  virtual ~MessageToken();

  MessageToken(const MessageToken& from);

  inline MessageToken& operator=(const MessageToken& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MessageToken& default_instance();

  void Swap(MessageToken* other);

  // implements Message ----------------------------------------------

  MessageToken* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MessageToken& from);
  void MergeFrom(const MessageToken& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string token = 1;
  inline bool has_token() const;
  inline void clear_token();
  static const int kTokenFieldNumber = 1;
  inline const ::std::string& token() const;
  inline void set_token(const ::std::string& value);
  inline void set_token(const char* value);
  inline void set_token(const char* value, size_t size);
  inline ::std::string* mutable_token();
  inline ::std::string* release_token();
  inline void set_allocated_token(::std::string* token);

  // required int64 expire = 2;
  inline bool has_expire() const;
  inline void clear_expire();
  static const int kExpireFieldNumber = 2;
  inline ::google::protobuf::int64 expire() const;
  inline void set_expire(::google::protobuf::int64 value);

  // required string address = 3;
  inline bool has_address() const;
  inline void clear_address();
  static const int kAddressFieldNumber = 3;
  inline const ::std::string& address() const;
  inline void set_address(const ::std::string& value);
  inline void set_address(const char* value);
  inline void set_address(const char* value, size_t size);
  inline ::std::string* mutable_address();
  inline ::std::string* release_address();
  inline void set_allocated_address(::std::string* address);

  // required int32 port = 4;
  inline bool has_port() const;
  inline void clear_port();
  static const int kPortFieldNumber = 4;
  inline ::google::protobuf::int32 port() const;
  inline void set_port(::google::protobuf::int32 value);

  // required int64 offset = 5;
  inline bool has_offset() const;
  inline void clear_offset();
  static const int kOffsetFieldNumber = 5;
  inline ::google::protobuf::int64 offset() const;
  inline void set_offset(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:MessageToken)
 private:
  inline void set_has_token();
  inline void clear_has_token();
  inline void set_has_expire();
  inline void clear_has_expire();
  inline void set_has_address();
  inline void clear_has_address();
  inline void set_has_port();
  inline void clear_has_port();
  inline void set_has_offset();
  inline void clear_has_offset();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* token_;
  ::google::protobuf::int64 expire_;
  ::std::string* address_;
  ::google::protobuf::int64 offset_;
  ::google::protobuf::int32 port_;
  friend void  protobuf_AddDesc_MessageToken_2eproto();
  friend void protobuf_AssignDesc_MessageToken_2eproto();
  friend void protobuf_ShutdownFile_MessageToken_2eproto();

  void InitAsDefaultInstance();
  static MessageToken* default_instance_;
};
// ===================================================================


// ===================================================================

// MessageToken

// required string token = 1;
inline bool MessageToken::has_token() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MessageToken::set_has_token() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MessageToken::clear_has_token() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MessageToken::clear_token() {
  if (token_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    token_->clear();
  }
  clear_has_token();
}
inline const ::std::string& MessageToken::token() const {
  // @@protoc_insertion_point(field_get:MessageToken.token)
  return *token_;
}
inline void MessageToken::set_token(const ::std::string& value) {
  set_has_token();
  if (token_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    token_ = new ::std::string;
  }
  token_->assign(value);
  // @@protoc_insertion_point(field_set:MessageToken.token)
}
inline void MessageToken::set_token(const char* value) {
  set_has_token();
  if (token_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    token_ = new ::std::string;
  }
  token_->assign(value);
  // @@protoc_insertion_point(field_set_char:MessageToken.token)
}
inline void MessageToken::set_token(const char* value, size_t size) {
  set_has_token();
  if (token_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    token_ = new ::std::string;
  }
  token_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:MessageToken.token)
}
inline ::std::string* MessageToken::mutable_token() {
  set_has_token();
  if (token_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    token_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:MessageToken.token)
  return token_;
}
inline ::std::string* MessageToken::release_token() {
  clear_has_token();
  if (token_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = token_;
    token_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void MessageToken::set_allocated_token(::std::string* token) {
  if (token_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete token_;
  }
  if (token) {
    set_has_token();
    token_ = token;
  } else {
    clear_has_token();
    token_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:MessageToken.token)
}

// required int64 expire = 2;
inline bool MessageToken::has_expire() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MessageToken::set_has_expire() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MessageToken::clear_has_expire() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MessageToken::clear_expire() {
  expire_ = GOOGLE_LONGLONG(0);
  clear_has_expire();
}
inline ::google::protobuf::int64 MessageToken::expire() const {
  // @@protoc_insertion_point(field_get:MessageToken.expire)
  return expire_;
}
inline void MessageToken::set_expire(::google::protobuf::int64 value) {
  set_has_expire();
  expire_ = value;
  // @@protoc_insertion_point(field_set:MessageToken.expire)
}

// required string address = 3;
inline bool MessageToken::has_address() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MessageToken::set_has_address() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MessageToken::clear_has_address() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MessageToken::clear_address() {
  if (address_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    address_->clear();
  }
  clear_has_address();
}
inline const ::std::string& MessageToken::address() const {
  // @@protoc_insertion_point(field_get:MessageToken.address)
  return *address_;
}
inline void MessageToken::set_address(const ::std::string& value) {
  set_has_address();
  if (address_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    address_ = new ::std::string;
  }
  address_->assign(value);
  // @@protoc_insertion_point(field_set:MessageToken.address)
}
inline void MessageToken::set_address(const char* value) {
  set_has_address();
  if (address_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    address_ = new ::std::string;
  }
  address_->assign(value);
  // @@protoc_insertion_point(field_set_char:MessageToken.address)
}
inline void MessageToken::set_address(const char* value, size_t size) {
  set_has_address();
  if (address_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    address_ = new ::std::string;
  }
  address_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:MessageToken.address)
}
inline ::std::string* MessageToken::mutable_address() {
  set_has_address();
  if (address_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    address_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:MessageToken.address)
  return address_;
}
inline ::std::string* MessageToken::release_address() {
  clear_has_address();
  if (address_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = address_;
    address_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void MessageToken::set_allocated_address(::std::string* address) {
  if (address_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete address_;
  }
  if (address) {
    set_has_address();
    address_ = address;
  } else {
    clear_has_address();
    address_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:MessageToken.address)
}

// required int32 port = 4;
inline bool MessageToken::has_port() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void MessageToken::set_has_port() {
  _has_bits_[0] |= 0x00000008u;
}
inline void MessageToken::clear_has_port() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void MessageToken::clear_port() {
  port_ = 0;
  clear_has_port();
}
inline ::google::protobuf::int32 MessageToken::port() const {
  // @@protoc_insertion_point(field_get:MessageToken.port)
  return port_;
}
inline void MessageToken::set_port(::google::protobuf::int32 value) {
  set_has_port();
  port_ = value;
  // @@protoc_insertion_point(field_set:MessageToken.port)
}

// required int64 offset = 5;
inline bool MessageToken::has_offset() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void MessageToken::set_has_offset() {
  _has_bits_[0] |= 0x00000010u;
}
inline void MessageToken::clear_has_offset() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void MessageToken::clear_offset() {
  offset_ = GOOGLE_LONGLONG(0);
  clear_has_offset();
}
inline ::google::protobuf::int64 MessageToken::offset() const {
  // @@protoc_insertion_point(field_get:MessageToken.offset)
  return offset_;
}
inline void MessageToken::set_offset(::google::protobuf::int64 value) {
  set_has_offset();
  offset_ = value;
  // @@protoc_insertion_point(field_set:MessageToken.offset)
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MessageToken_2eproto__INCLUDED
