// Classes and structures being serialized

// Generated by ProtocolBuffer
// - a pure c# code generation implementation of protocol buffers
// Report bugs to: https://silentorbit.com/protobuf/

// DO NOT EDIT
// This file will be overwritten when CodeGenerator is run.
// To make custom modifications, edit the .proto file and add //:external before the message line
// then write the code and the changes in a separate file.
using System;
using System.Collections.Generic;

namespace Message
{
    public partial class MessageToken
    {
        public List<string> Token { get; set; }

        public List<long> Expire { get; set; }

        public List<string> Address { get; set; }

        public List<int> Port { get; set; }

        public List<long> BlockId { get; set; }

        public List<long> Index { get; set; }

        public List<long> Size { get; set; }

        public List<long> Offset { get; set; }

    }

}
